name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install PostCSS and autoprefixer
        run: |
          npm install -g postcss postcss-cli autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        run: |
          mkdir ../hugo_site
          mv public/* ../hugo_site/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch
          git checkout master
          cp -r ../hugo_site/* .
          git add .
          git commit -m "Deploy Hugo site to GitHub Pages" || exit 0
          git push origin master